### ISSUE TITLE
你好，请问全屏的属性怎么设置？

### ISSUE THREAD

**Issue by yliang82** [wangruning/React-Native-VideoPlayer#1]
还有其他的属性，谢谢！

**Comment by l0neman** [comment]
@yliang82  不好意思了╮(╯Д╰)╭，暂时就只有这几种属性，你可以改改代码，让它支持全屏

resizeMode='contain'    //模式
uri='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'  //路径
autoPlay={false}  //自动播放
